
export WANDB_MODE=offline
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr5e-3 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --lr 5e-3 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr1e-3 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --lr 1e-3 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr5e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --lr 5e-4 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr1e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --lr 1e-4 --wdecay 1e-3

#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr5e-4_debug --module_type resnet_block --batch_size=50 --depth 5 --redo_final_test 1 --epochs 10 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --lr 5e-4 --wdecay 1e-3

#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr2e-4 --lr 2e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr3e-4 --lr 3e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr4e-4 --lr 4e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr5e-4 --lr 5e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr6e-4 --lr 6e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr7e-4 --lr 7e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr8e-4 --lr 8e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cgqa_lr9e-4 --lr 9e-4 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
