
export WANDB_MODE=offline
#CUDA_VISIBLE_DEVICES=1 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cobj_lr4e-4 --lr 4e-4 --n_tasks 3 --dataset cobj --seed 1234 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cobj --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 0

#CUDA_VISIBLE_DEVICES=1 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cobj_10tasks_lr4e-4 --lr 4e-4 --n_tasks 10 --dataset cobj --seed 1234 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cobj --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 0

CUDA_VISIBLE_DEVICES=1 python3 mntdp_cgqa.py --exp_name mntdp_resnet18_cobj_5tasks_lr4e-4 --lr 4e-4 --n_tasks 5 --dataset cobj --seed 1234 --module_type resnet_block --batch_size=100 --depth 5 --redo_final_test 1 --epochs 100 --momentum_bn 0.1 --pr_name mntdp_resnet18_cobj --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 0

# vit
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_vit_cgqa_lr1e-4 --lr 1e-4 --module_type vit_block --hidden_size=384 --batch_size=100 --depth 5 --redo_final_test 1 --epochs 200 --dataset cgqa --image_size 224 --momentum_bn 0.1 --pr_name mntdp_vit_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_vit_cgqa_lr5e-4 --lr 5e-4 --module_type vit_block --hidden_size=384 --batch_size=100 --depth 5 --redo_final_test 1 --epochs 200 --dataset cgqa --image_size 224 --momentum_bn 0.1 --pr_name mntdp_vit_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_vit_cgqa_lr1e-3 --lr 1e-3 --module_type vit_block --hidden_size=384 --batch_size=100 --depth 5 --redo_final_test 1 --epochs 200 --dataset cgqa --image_size 224 --momentum_bn 0.1 --pr_name mntdp_vit_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
#CUDA_VISIBLE_DEVICES=0 python3 mntdp_cgqa.py --exp_name mntdp_vit_cgqa_lr5e-5 --lr 5e-5 --module_type vit_block --hidden_size=384 --batch_size=100 --depth 5 --redo_final_test 1 --epochs 200 --dataset cgqa --image_size 224 --momentum_bn 0.1 --pr_name mntdp_vit_cgqa --copy_batchstats 1 --track_running_stats_bn 1 --task_sequence s_minus --gating MNTDP --shuffle_test 0 --wdecay 1e-3
